import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SidebarProvider>
        <AppSidebar />
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <SidebarTrigger className="fixed top-4 left-4 z-50" />
            {children}
          </body>
      </SidebarProvider>
    </html>
  );
}
